django_roles/core/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # PAGINA DE INICIO
    path("", HomeView.as_view(), name="home"),
    # PAGINA DE PRECIOS
    path("pricing/", PricingView.as_view(), name="pricing"),
    # # PAGINA DE PREGUNTAS Y RESPUESTAS / PAGINA DE ACERCA DE (A CARGO DE LOS SEGUIDORES DEL CANAL)
    # # PAGINAS DE LOGIN Y REGISTRO (VIDEO 5)
    path("register/", RegisterView.as_view(), name="register"),
    # # PAGINAS DE PERFIL: VISTA DE PERFIL - EDICION DEL PERFIL (VIDEO 8)
    # path('profile/', login_required(ProfileView.as_view()), name='profile'),
    # # PAGINAS QUE ADMINISTRAN LOS CURSOS: LA LISTA DE CURSOS - (LA CREACION DE CURSOS - LA EDICION DE CURSOS - LA ELIMINACION DE CURSOS) (VIDEO 10)
    # path('courses/', CoursesView.as_view(), name='courses'),
    # path('courses/create/', login_required(CourseCreateView.as_view()), name='course_create'),
    # path('courses/<int:pk>/edit/', login_required(CourseEditView.as_view()), name='course_edit'),
    # path('courses/<int:pk>/delete/', login_required(CourseDeleteView.as_view()), name='course_delete'),
    # # INSCRIPCION DE UN ALUMNO EN UN CURSO
    # path('enroll_course/<int:course_id>', login_required(CourseEnrollmentView.as_view()), name='enroll_course'),
    # path('error/', login_required(ErrorView.as_view()), name='error'),
    # # PAGINA DE VISTA DE INSCRIPCION
    # # PAGINAS ADMINISTRACION DE NOTAS: (LISTA DE ESTUDIANTES POR CURSO - EDICION DE NOTAS)
    # path('courses/<int:course_id>', login_required(StudentListMarkView.as_view()), name='student_list_mark'),
    # path('courses/update_mark/<int:mark_id>', login_required(UpdateMarkView.as_view()), name='update_mark'),
    # # PAGINAS DE ASISTENCIAS: (LISTA DE ESTUDIANTES POR CURSO - AGREGAR ASISTENCIAS)
    # path('course/<int:course_id>/list_attendance/', login_required(AttendanceListView.as_view()), name='list_attendance'),
    # path('course/<int:course_id>/add_attendance/', login_required(AddAttendanceView.as_view()), name='add_attendance'),
    # # EVOLUCION DEL ESTUDIANTE
    # path('evolution/<int:course_id>/<int:student_id>/', login_required(evolution), name='evolution'),
    # # CAMBIO DE CONTRASEÑA
    # path('password_change/', login_required(ProfilePasswordChangeView.as_view()), name='profile_password_change'),
    # # AGREGAR NUEVO USUARIO
    # path('add_user/', AddUserView.as_view(), name='add_user'),
    # # NUEVO LOGIN
    # path('login/', CustomLoginView.as_view(), name='custom_login'),
    # # VISUALIZAR EL PERFIL DE UN USUARIO
    # path('user_details/<int:pk>/', UserDetailsView.as_view(), name='user_details'),
    # # EDITAR DATOS DEL USUARIO
    # path('superuser_edit/<int:user_id>/', login_required(superuser_edit), name='superuser_edit'),
]

django_roles/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
import uuid  # Requerida para las instancias de tuplas únicas


# CURSOS: ESTADOS POSIBLES(STATUS): EN ETAPA DE INSCRIPCION - EN DESARROLLO - FINALIZADO
class Course(models.Model):
    STATUS_CHOICES = (
        ("I", "En etapa de inscripción"),
        ("P", "En progreso"),
        ("F", "Finalizado"),
    )

    name = models.CharField(max_length=90, verbose_name="Nombre")
    description = models.TextField(blank=True, null=True, verbose_name="Descripción")
    teacher = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"groups__name": "profesores"},
        verbose_name="Profesor",
    )
    class_quantity = models.PositiveIntegerField(
        default=0, verbose_name="Cantidad de clases"
    )
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default="I", verbose_name="Estado"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"


# INSCRIPCIONES
class Registration(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Curso")
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="students_registration",
        limit_choices_to={"groups__name": "estudiantes"},
        verbose_name="Estudiante",
    )
    enabled = models.BooleanField(default=True, verbose_name="Alumno Regular")

    def __str__(self):
        return f"{self.student.username} - {self.course.name}"

    class Meta:
        verbose_name = "Inscripción"
        verbose_name_plural = "Inscripciones"


# ASISTENCIAS
class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Curso")
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="attendances",
        limit_choices_to={"groups__name": "estudiantes"},
        verbose_name="Estudiante",
    )
    date = models.DateField(null=True, blank=True, verbose_name="Fecha")
    present = models.BooleanField(
        default=False, blank=True, null=True, verbose_name="Presente"
    )

    def __str__(self):
        return f"Asistencia {self.id}"

    # Lógica para generar el estado del alumno regular / irregular (enabled)
    # total-clases => class_quantity del modelo Course
    # total-inasistencias => attendance -> present = False
    # porcentaje-inasistencias = (total-inasistencias / total-clases) * 100 -------> >20 (>20%) => alumno es irregular => enabled = False
    # total-clases = 10
    # total-inasistencias = 4
    # porcentaje-inasistencias = (4 / 10) * 100 = 40 % => seria un alumno irregular

    def update_registration_enabled_status(self):
        course_instance = Course.objects.get(id=self.course.id)
        total_classes = course_instance.class_quantity
        total_absences = Attendance.objects.filter(
            student=self.student, course=self.course, present=False
        ).count()
        absences_percent = (total_absences / total_classes) * 100

        registration = Registration.objects.get(
            course=self.course, student=self.student
        )

        if absences_percent > 20:
            registration.enabled = False
        else:
            registration.enabled = True

        registration.save()

    class Meta:
        verbose_name = "Asistencia"
        verbose_name_plural = "Asistencias"


# NOTAS
class Mark(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Curso")
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"groups__name": "estudiantes"},
        verbose_name="Estudiante",
    )
    mark_1 = models.PositiveIntegerField(null=True, blank=True, verbose_name="Nota 1")
    mark_2 = models.PositiveIntegerField(null=True, blank=True, verbose_name="Nota 2")
    mark_3 = models.PositiveIntegerField(null=True, blank=True, verbose_name="Nota 3")
    average = models.DecimalField(
        max_digits=3, decimal_places=1, null=True, blank=True, verbose_name="Promedio"
    )

    def __str__(self):
        return str(self.course)

    # Calcular el promedio (llamo a una función)
    def calculate_average(self):
        marks = [self.mark_1, self.mark_2, self.mark_3]
        valid_marks = [mark for mark in marks if mark is not None]
        if valid_marks:
            return sum(valid_marks) / len(valid_marks)
        return None

    def save(self, *args, **kwargs):
        # Verifico si alguna nota cambio
        if self.mark_1 or self.mark_2 or self.mark_3:
            self.average = (
                self.calculate_average()
            )  # Calcular el promedio (llamo a una función)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Nota"
        verbose_name_plural = "Notas"


class Provincias(models.Model):
    id_pv = models.CharField(
        primary_key=True,
        max_length=200,
        help_text="ID único para cada provincia",
    )
    nomb_pv = models.CharField(max_length=200)

    ESTADOS_TUPLA = (
        ("h", "Habilitado"),
        ("d", "Desahabilitado"),
    )

    hab_pv = models.CharField(
        max_length=1,
        choices=ESTADOS_TUPLA,
        blank=True,
        default="h",
    )

    class Meta:
        ordering = ["nomb_pv"]
        verbose_name = "Provincia"

    def __str__(self):
        return "%s (%s)" % (self.id_pv, self.nomb_pv)


class Localidades(models.Model):
    cod_post_lc = models.CharField(
        primary_key=True,
        max_length=6,
        help_text="ID único para cada localidad",
    )
    nomb_lc = models.CharField(max_length=200)
    id_pv = models.ForeignKey(Provincias, on_delete=models.CASCADE, null=True)

    ESTADOS_TUPLA = (
        ("h", "Habilitado"),
        ("d", "Desahabilitado"),
    )

    hab_lc = models.CharField(
        max_length=1,
        choices=ESTADOS_TUPLA,
        blank=True,
        default="h",
    )

    class Meta:
        ordering = ["nomb_lc"]
        verbose_name = "Localidad"
        verbose_name_plural = "Localidades"

    def __str__(self):
        return "%s (%s)" % (self.cod_post_lc, self.nomb_lc)


class Eventos(models.Model):
    id_ev = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="ID único para cada evento",
    )
    nomb_ev = models.CharField(max_length=200)
    desc_ev = models.CharField(max_length=200)
    fec_ini_ev = models.DateField(null=True, blank=True)
    fec_fin_ev = models.DateField(null=True, blank=True)
    pr_ev = models.DecimalField(max_digits=10, decimal_places=2)

    ESTADOS_TUPLA = (
        ("h", "Habilitado"),
        ("d", "Desahabilitado"),
        ("s", "Suspendido"),
        ("f", "Finalizado"),
        ("a", "Actualizado"),
    )

    hab_ev = models.CharField(
        max_length=1,
        choices=ESTADOS_TUPLA,
        blank=True,
        default="h",
    )

    class Meta:
        ordering = ["fec_ini_ev"]
        verbose_name = "Evento"

    def __str__(self):
        return "%s (%s)" % (self.nomb_ev, self.desc_ev)

    def muestra_estado(self):
        if self.hab_ev:
            # Convierto a diccionaria el valor estado ejemplar
            ESTADOS_TUPLA = {
                ("h", "Habilitado"),
                ("d", "Desahabilitado"),
                ("s", "Suspendido"),
                ("f", "Finalizado"),
                ("a", "Actualizado"),
            }
            # Retornar el valor correspondiente
            return ESTADOS_TUPLA.get(self.estado)
        return None

    # Funcion para actualizar el estado de los boletos si es que se actualiza el evento (No necesario, usado para pruebas)
    def seActualizo(self):
        boletos = Boletos.objects.filter(evt_bl=self)
        for boleto in boletos:
            if not boleto.enVenta_bl:
                boleto.enVenta_bl = True
                boleto.save()


class LugaresDeEvento(models.Model):
    id_le = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="ID único para cada evento",
    )
    desc_le = models.CharField(max_length=200)
    tel_le = models.CharField(max_length=15)
    lat_le = models.DecimalField(max_digits=10, decimal_places=7)
    lng_le = models.DecimalField(max_digits=10, decimal_places=7)

    cod_post_lc = models.ForeignKey(Localidades, on_delete=models.CASCADE, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.

    ESTADOS_TUPLA = (
        ("h", "Habilitado"),
        ("d", "Desahabilitado"),
        ("s", "Suspendido"),
        ("f", "Finalizado"),
    )

    hab_ev = models.CharField(
        max_length=1,
        choices=ESTADOS_TUPLA,
        blank=True,
        default="h",
    )

    class Meta:
        ordering = ["id_le"]
        verbose_name = "Lugar de Evento"

    def __str__(self):
        return "%s (%s)" % (self.id_le, self.desc_le)


class Ventas(models.Model):
    id_ve = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="ID único para cada venta",
    )
    cli_ve = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        # Con esto limitamos a que se puedan agregar solo clientes
        limit_choices_to={"groups__name": "clientes"},
        verbose_name="Cliente",
    )
    evt_ve = models.ForeignKey(
        Eventos,
        on_delete=models.CASCADE,
        null=True,
        verbose_name="Evento",
    )
    pr_ve = models.DecimalField(max_digits=10, decimal_places=2)

    def save(self, *args, **kwargs):
        # Si es el mismo evento con el que se creo la venta no modificar el precio
        if self._state.adding:
            if self.evt_ve:

django_roles/templates/profile/admin-courses.html
<h5>Todos los Cursos</h5>
{% if inscription_courses %}
	<div class="alert alert-success" role="alert">
		<h5>Cursos en etapa de Inscripción</h5>
	</div>
	<table class="table table-success table-striped">
		<thead>
			<tr>
				<th scope="col">Nombre del Curso</th>
				<th scope="col">Profesor</th>
				<th class="text-center" scope="col">Cant.Clases</th>
				<th class="text-center" scope="col">Cant.Alumnos</th>
				<th class="text-center" scope="col">Acciones</th>
			</tr>
		</thead>
		<tbody>
			{% for course in inscription_courses %}
				{% with enrollment_count=course.registration_set.count %}
				<tr>
					<td>{{ course.name }}</td>
					<td>{{ course.teacher.get_full_name }}</td>
					<td class="text-center">{{ course.class_quantity }}</td>
					<td class="text-center">{{ enrollment_count }}</td>
					<td class="text-center">
						<button class="btn btn-sm btn-info">Info</button>
						<a class="btn btn-sm btn-warning" href="{% url 'course_edit' course.id %}">Editar</a>
					</td>
				</tr>
				{% endwith %}
			{% endfor %}
		</tbody>
	</table>
{% endif %}

{% if progress_courses %}
	<div class="alert alert-warning" role="alert">
		<h5>Cursos en Progreso</h5>
	</div>
	<table class="table table-warning table-striped">
		<thead>
			<tr>
				<th scope="col">Nombre del Curso</th>
				<th scope="col">Profesor</th>
				<th class="text-center" scope="col">Cant.Clases</th>
				<th class="text-center" scope="col">Cant.Alumnos</th>
				<th class="text-center" scope="col">Acciones</th>
			</tr>
		</thead>
		<tbody>
			{% for course in progress_courses %}
				{% with enrollment_count=course.registration_set.count %}
				<tr>
					<td>{{ course.name }}</td>
					<td>{{ course.teacher.get_full_name }}</td>
					<td class="text-center">{{ course.class_quantity }}</td>
					<td class="text-center">{{ enrollment_count }}</td>
					<td class="text-center">
						<button class="btn btn-sm btn-info">Info</button>
					</td>
				</tr>
				{% endwith %}
			{% endfor %}
		</tbody>
	</table>
{% endif %}

{% if finalized_courses %}
	<div class="alert alert-danger" role="alert">
		<h5>Cursos Finalizados</h5>
	</div>

	<table class="table table-danger table-striped">
		<thead>
			<tr>
				<th scope="col">Nombre del Curso</th>
				<th scope="col">Profesor</th>
				<th class="text-center" scope="col">Cant.Clases</th>
				<th class="text-center" scope="col">Cant.Alumnos</th>
				<th class="text-center" scope="col">Acciones</th>
			</tr>
		</thead>
		<tbody>
			{% for course in finalized_courses %}
				{% with enrollment_count=course.registration_set.count %}
				<tr>
					<td>{{ course.name }}</td>
					<td>{{ course.teacher.get_full_name }}</td>
					<td class="text-center">{{ course.class_quantity }}</td>
					<td class="text-center">{{ enrollment_count }}</td>
					<td class="text-center">
						<button class="btn btn-sm btn-info">Info</button>
					</td>
				</tr>
				{% endwith %}
			{% endfor %}
		</tbody>
	</table>
{% endif %}

<a class="btn btn-success" href="{% url 'course_create' %}">Agregar Curso</a>

django_roles/templates/profile/admin-users.html
<h5>Todos los Usuarios</h5>

<table class="table">
	<thead>
		<tr>
			<th scope="col">Nombre y Apellido</th>
			<th scope="col">Usuario</th>
			<th scope="col">Rol</th>
			<th class="text-center" scope="col">Acciones</th>
		</tr>
	</thead>

	<tbody>
		{% for user_profile in user_profiles %}

		{% if user_profile.groups|join:", " == 'estudiante' %}
			<tr class="table-primary">
		{% elif user_profile.groups|join:", " == 'profesor' %}
			<tr class="table-success">
		{% elif user_profile.groups|join:", " == 'preceptor' %}
			<tr class="table-secondary">
		{% elif user_profile.groups|join:", " == 'administrativo' %}
			<tr class="table-danger">
		{% endif %}
			<th scope="row">{{ user_profile.user.get_full_name }}</th>
			<td>{{ user_profile.user.username }}</td>
			<td>{{ user_profile.groups|join:", "|capfirst }}</td>
			<td class="text-center">
				<a class="btn btn-sm btn-info" href="{% url 'user_details' user_profile.user.id %}">Ver Información</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

<a class="btn btn-primary" href="{% url 'add_user' %}">Agregar Usuario</a>

django_roles/templates/profile/admin.html
<div>
    <h5>Herramientas Administrativas</h5>
    <ul class="nav nav-tabs nav-fill">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#usuarios" data-bs-toggle="tab">Usuarios</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#cursos" data-bs-toggle="tab">Cursos</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active mt-2" id="usuarios">
            {% include 'profile/admin-users.html' %}
        </div>

        <div class="tab-pane fade show mt-2" id="cursos">
            {% include 'profile/admin-courses.html' %}
        </div>
    </div>
</div>

django_roles/templates/profile/change_password.html
{% extends 'base.html' %}

{% block content %}


<div class="container my-4">
	<h2>Cambiar Contraseña</h2>
	{% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

	<div class="row">
		<div class="col-6">
			<div class="card mx-auto">
				<div class="card-body">
					<form action="{% url 'profile_password_change' %}" method="post">
						{%  csrf_token %}

						<div class="mb-3">
							<label for="old_password">Contraseña actual</label>
							<input class="form-control" type="password" name="old_password" id="old_password">
						</div>

						<div class="mb-3">
							<label for="new_password1">Nueva Contraseña</label>
							<input class="form-control" type="password" name="new_password1" id="new_password1">
						</div>

						<div class="mb-3">
							<label for="new_password2">Confirmar nueva Contraseña</label>
							<input class="form-control" type="password" name="new_password2" id="new_password2">
						</div>

						<input class="btn btn-primary" type="submit" value="Cambiar Contraseña" {% if password_changed %}disabled{% endif %}>
					</form>
				</div>
			</div>
		</div>
		<div class="col-6">

			<div class="card mx-auto">
				<div class="card-body">
					<h5 class="card-title">Su contraseña...</h5>
					<ul>
						<li>No puede ser similar a otros componentes de su información personal.</li>
						<li>Debe contener por lo menos 8 caracteres.</li>
						<li>No puede ser una contraseña usada muy comúnmente.</li>
						<li>No puede estar formada exclusivamente por números.</li>
					</ul>
				</div>
			</div>
		</div>		
	</div>
</div>

{% endblock %}

django_roles/templates/profile/preceptor.html
<h5>TODOS LOS CURSOS</h5>

<div class="card text-bg-warning shadow mt-3 mb-3">
	<div class="card-header">CURSOS EN PROGRESO</div>
	<div class="card-body">
		{% if progress_courses %}

			<ul class="list-group">
				{% for course in progress_courses %}
					{% with enrollment_count=course.registration_set.count %}
						<li class="list-group-item list-group-item-warning">
							{{ course.name }}
							<a href="{% url 'list_attendance' course.id %}"
							   class="btn btn-sm btn-warning float-end">
								{% if course.status == 'P' %}
									Asistencias
								{% endif %}
								<span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
							</a>
						</li>
					{% endwith %}
				{% endfor %}
			</ul>
		{% else %}
			<div class="alert alert-warning" role="alert">
				No hay Cursos en progreso hasta el momento
			</div>
		{% endif %}
	</div>
</div>

<div class="card text-bg-success shadow mb-3">
	<div class="card-header">CURSOS EN ETAPA DE INSCRIPCION</div>
	<div class="card-body">
		{% if inscription_courses %}
			<ul class="list-group">
				{% for course in inscription_courses %}
					{% with enrollment_count=course.registration_set.count %}
						<li class="list-group-item list-group-item-success">
							{{ course.name }}
							<a href="{% url 'list_attendance' course.id %}"
							   class="btn btn-sm btn-success float-end">
								{% if course.status == 'I' %}
									Consultar listado
								{% endif %}
								<span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
							</a>
						</li>
					{% endwith %}
				{% endfor %}
			</ul>
		{% else %}
			<div class="alert alert-success" role="alert">
				No hay Cursos en estado de inscripcion hasta el momento
			</div>
		{% endif %}
	</div>
</div>

<div class="card text-bg-danger shadow mb-3">
	<div class="card-header">CURSOS FINALIZADOS</div>
	<div class="card-body">
		{% if finalized_courses %}
			<ul class="list-group">
				{% for course in finalized_courses %}
					{% with enrollment_count=course.registration_set.count %}
						<li class="list-group-item list-group-item-danger">
							{{ course.name }}
							<a href="{% url 'list_attendance' course.id %}"
							   class="btn btn-sm btn-danger float-end">
								{% if course.status == 'F' %}
									Consultar listado
								{% endif %}
								<span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
							</a>
						</li>
					{% endwith %}
				{% endfor %}
			</ul>
		{% else %}
			<div class="alert alert-danger" role="alert">
				No hay Cursos finalizados hasta el momento
			</div>
		{% endif %}
	</div>
</div>

django_roles/templates/profile/profesor.html
<h5>CURSOS ASIGNADOS</h5>

<div class="card text-bg-warning shadow mt-3 mb-3">
	<div class="card-header">CURSOS EN PROGRESO</div>
	<div class="card-body">
		{% if progress_courses %}
			<ul class="list-group">
				{% for course in progress_courses %}
					{% with enrollment_count=course.registration_set.count %}
						<li class="list-group-item list-group-item-warning">
							{{ course.name }}
							<a href="{% url 'student_list_mark' course.id %}"
							   class="btn btn-sm btn-warning float-end">
								{% if course.status == 'P' %}
									Agregar Notas
								{% endif %}
								<span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
							</a>
						</li>
					{% endwith %}
				{% endfor %}
			</ul>
		{% else %}
			<div class="alert alert-warning" role="alert">
				No tiene Cursos en progreso asignados hasta el momento
			</div>
		{% endif %}
	</div>
</div>

<div class="card text-bg-success shadow mb-3">
	<div class="card-header">CURSOS EN ETAPA DE INSCRIPCION</div>
	<div class="card-body">
		{% if inscription_courses %}
			<ul class="list-group">
				{% for course in inscription_courses %}
					{% with enrollment_count=course.registration_set.count %}
						<li class="list-group-item list-group-item-success">
							{{ course.name }}
							<a href="{% url 'student_list_mark' course.id %}"
							   class="btn btn-sm btn-success float-end">
								{% if course.status == 'I' %}
									Consultar listado
								{% endif %}
								<span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
							</a>
						</li>
					{% endwith %}
				{% endfor %}
			</ul>
		{% else %}
			<div class="alert alert-success" role="alert">
				No tiene Cursos en estado de inscripcion asignados hasta el momento
			</div>
		{% endif %}
	</div>
</div>

<div class="card text-bg-danger shadow mb-3">
	<div class="card-header">CURSOS FINALIZADOS</div>
	<div class="card-body">
		{% if finalized_courses %}
			<ul class="list-group">
				{% for course in finalized_courses %}
					{% with enrollment_count=course.registration_set.count %}
						<li class="list-group-item list-group-item-danger">
							{{ course.name }}
							<a href="{% url 'student_list_mark' course.id %}" class="btn btn-sm btn-danger float-end">
								{% if course.status == 'F' %}
									Consultar listado
								{% endif %}
								<span class="badge rounded-pill bg-light text-danger">{{ enrollment_count }}</span>
							</a>
						</li>
					{% endwith %}
				{% endfor %}
			</ul>
		{% else %}
			<div class="alert alert-danger" role="alert">
				No tiene Cursos finalizados asignados hasta el momento
			</div>
		{% endif %}
	</div>
</div>