dmProject/dashboard/urls.py
from django.urls import path
from dashboard import views

urlpatterns = [
    path("data/", views.chart_data, name="chart_data"),
    path("", views.chart_view, name="chart_view"),
]

dmProject/dmProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('dashboard/admin/', admin.site.urls),
    # path('dashboard/', include('dashboard.urls')),
    path("mapp/admin/", admin.site.urls),
    path("mapp/", include("mapp.urls")),
]

dmProject/mapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from .views import MarkersMapView, showroute, showmap
from . import views

app_name = "mapp"
urlpatterns = [
    path("<str:lat1>/<str:long1>/<str:lat2>/<str:long2>/", showroute, name="showroute"),
    path("", showmap, name="showmap"),
]

dmProject/dashboard/views.py
# Create your views here.
from django.shortcuts import render
import pandas as pd
from django.templatetags.static import static
from django.http import JsonResponse


def chart_data(request):
    df = pd.read_csv("dashboard/static/car_sales.csv")
    rs = df.groupby("Engine_size")["Sales_in_thousands"].agg("sum")
    categories = list(rs.index)
    values = list(rs.values)
    chart_data = {
        "label": "Line Chart",
        "labels": categories,
        "values": values,
        "chart_type": "bar",
    }
    return JsonResponse(chart_data)


def chart_view(request):
    return render(request, "chart.html", {})

dmProject/mapp/views.py
from django.views.generic.base import TemplateView
import folium
from django.shortcuts import render, redirect
from .utils import get_route


class MarkersMapView(TemplateView):
    template_name = "map.html"


def showmap(request):
    return render(request, "showMap.html")


def showroute(request, lat1, long1, lat2, long2):
    figure = folium.Figure()
    lat1, long1, lat2, long2 = float(lat1), float(long1), float(lat2), float(long2)

    route = get_route(long1, lat1, long2, lat2)

    m = folium.Map(location=[lat1, long1], zoom_start=10)
    m.add_to(figure)

    folium.PolyLine(route["route"], weight=8, color="blue", opacity=0.6).add_to(m)
    folium.Marker(
        location=[lat1, long1], icon=folium.Icon(icon="play", color="green")
    ).add_to(m)
    folium.Marker(
        location=[lat2, long2], icon=folium.Icon(icon="stop", color="red")
    ).add_to(m)

    figure.render()
    context = {"map": figure}

    return render(request, "showRoute.html", context)

dmProject/dashboard/templates/chart.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>DW2024: Chart.js Example</title>
    <!-- Include Chart.js via CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
    <div style="width: 50%; margin: 0 auto;">
        <canvas id="myChart"></canvas>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            fetch('http://127.0.0.1:8000/dashboard/data/')
                .then(response => response.json())
                .then(data => {
                    const ctx = document.getElementById('myChart').getContext('2d');

                    new Chart(ctx, {
                        type: data.chart_type,
                        data: {
                            labels: data.labels,
                            datasets: [{
                                label: data.label,
                                data: data.values,
                            }]
                        },
                        options: {
                            scales: {
                                y: {
                                    beginAtZero: true
                                }
                            }
                        }
                    });
                });
        });
    </script>
</body>

</html>

dmProject/mapp/templates/map.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Markers Map</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'map.css' %}" />
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet/dist/leaflet.css" crossorigin="" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js" crossorigin=""></script>
</head>

<body>
    <div id="map"></div>
    <script src="{% static 'map.js' %}" defer></script>
</body>

</html>

dmProject/mapp/templates/showMap.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Map to find route</title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />

    <!-- Load Leaflet from CDN -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>

    <!-- Load Esri Leaflet from CDN -->
    <script src="https://unpkg.com/esri-leaflet@2.5.0/dist/esri-leaflet.js"
        integrity="sha512-ucw7Grpc+iEQZa711gcjgMBnmd9qju1CICsRaryvX7HJklK0pGl/prxKvtHwpgm5ZHdvAil7YPxI1oWPOWK3UQ=="
        crossorigin=""></script>

    <!-- Load Esri Leaflet Geocoder from CDN -->
    <link rel="stylesheet" href="https://unpkg.com/esri-leaflet-geocoder@2.3.3/dist/esri-leaflet-geocoder.css"
        integrity="sha512-IM3Hs+feyi40yZhDH6kV8vQMg4Fh20s9OzInIIAc4nx7aMYMfo+IenRUekoYsHZqGkREUgx0VvlEsgm7nCDW9g=="
        crossorigin="">
    <script src="https://unpkg.com/esri-leaflet-geocoder@2.3.3/dist/esri-leaflet-geocoder.js"
        integrity="sha512-HrFUyCEtIpxZloTgEKKMq4RFYhxjJkCiF5sDxuAokklOeZ68U2NPfh4MFtyIVWlsKtVbK5GD2/JzFyAfvT5ejA=="
        crossorigin=""></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
        }
    </style>
</head>

<body>

    <input type="hidden" id="lat11" name="lat11" value="1.01" />
    <input type="hidden" id="lon11" name="lon11" value="1.21" />
    <input type="hidden" id="lat22" name="lat22" value="2.05" />
    <input type="hidden" id="lon22" name="lon22" value="2.15" />


    <div id="map"></div>
    <script>
        var map = L.map('map').setView([11, 79], 10);
        data = {};
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        var gcs = L.esri.Geocoding.geocodeService();
        var count = 0;


        map.on('click', (e) => {
            count += 1;
            gcs.reverse().latlng(e.latlng).run((err, res) => {
                if (err) return;
                L.marker(res.latlng).addTo(map).bindPopup(res.address.Match_addr).openPopup();
                k = count.toString()
                data[k + 'lat'] = res.latlng['lat'];
                data[k + 'lon'] = res.latlng['lng'];


                if (count == 1) {

                    $('#lat11').val(res.latlng['lat']);
                    $('#lon11').val(res.latlng['lng']);

                }


                if (count == 2) {

                    $('#lat22').val(res.latlng['lat']);
                    $('#lon22').val(res.latlng['lng']);



                    var lat11 = document.getElementById('lat11').value;
                    var lon11 = document.getElementById('lon11').value;
                    var lat22 = document.getElementById('lat22').value;
                    var lon22 = document.getElementById('lon22').value;


                    var baseurl = "{% url 'mapp:showroute' 1.01 1.11 2.01 2.11 %}";

                    window.location.replace(baseurl.substring(0, 6) + lat11 + '/' + lon11 + '/' + lat22 + '/' + lon22);
                    count = 0;



                }


            });


        });
    </script>
</body>

dmProject/mapp/templates/showRoute.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Route between the locations</title>
    {{map.header.render|safe}}
</head>

<body>
    {% if map %}
    {{map.html.render|safe}}
    <script>
        {{map.script.render | safe}}
    </script>
    {% endif %}
</body>

</html>